### ISSUE TITLE
 Coinhive JavaScript cryptocoin miner

### ISSUE THREAD

**Issue by veera83372** [arguiot/EyeJS#13]
Hey @arguiot, Sophos in my system detected  Coinhive JavaScript crypto coin miner in your docs

**Comment by arguiot** [comment]
I've dropped CoinHive, see #6 and #7 for more details.

**Comment by arguiot** [comment]
And don't forget to leave a star ⭐️, 😊

**Comment by veera83372** [comment]
Just last night I cloned your DisplayJs  repo then I got to know that its dependent on eyeJs (at that time Sophos detected coinhive)

**Comment by arguiot** [comment]
Yeah, I need to update the dependencies, but while you’re not opening the website of the older version of EyeJS on your computer, it won’t mine bitcoins.
